import type { ResolvedTrack } from "@/types";
type SpotifyTrack={id:string;name:string;duration_ms?:number;external_urls:{spotify:string};artists:Array<{name:string}>;album?:{name?:string;images?:Array<{url:string}>}};
type AppleData={id?:string;trackId?:number|string;name?:string;trackName?:string;artistName:string;albumName?:string;collectionName?:string;url?:string;trackViewUrl?:string;artwork?:{url?:string};artworkUrl100?:string;durationInMillis?:number;trackTimeMillis?:number;wrapperType?:string};
type AppleResource={id?:string;attributes?:AppleData} & AppleData;
type DeezerData={id:number|string;title:string;duration?:number;link:string;artist?:{name?:string};album?:{title?:string;cover_xl?:string;cover_big?:string}};
export function artwork(url?: string | null, size=900){ return url?.replace("{w}",String(size)).replace("{h}",String(size)) ?? null; }
export function spotifyTrack(data:SpotifyTrack):ResolvedTrack{return {provider:"spotify",provider_track_id:data.id,source_url:data.external_urls.spotify,title:data.name,artist:data.artists.map(a=>a.name).join(", "),album:data.album?.name??null,artwork_url:data.album?.images?.[0]?.url??null,duration_ms:data.duration_ms??null,spotify_url:data.external_urls.spotify,apple_music_url:null,deezer_url:null,external_urls:{spotify:data.external_urls.spotify}}}
export function appleTrack(data:AppleResource):ResolvedTrack{const a=data.attributes??data;const id=String(data.id??a.trackId??"");const url=a.url??a.trackViewUrl??`https://music.apple.com/br/song/${id}`;return {provider:"apple",provider_track_id:id,source_url:url,title:a.name??a.trackName??"Faixa sem título",artist:a.artistName,album:a.albumName??a.collectionName??null,artwork_url:artwork(a.artwork?.url??a.artworkUrl100),duration_ms:a.durationInMillis??a.trackTimeMillis??null,spotify_url:null,apple_music_url:url,deezer_url:null,external_urls:{appleMusic:url}}}
export function deezerTrack(d:DeezerData):ResolvedTrack{return {provider:"deezer",provider_track_id:String(d.id),source_url:d.link,title:d.title,artist:d.artist?.name??"",album:d.album?.title??null,artwork_url:d.album?.cover_xl??d.album?.cover_big??null,duration_ms:d.duration?d.duration*1000:null,spotify_url:null,apple_music_url:null,deezer_url:d.link,external_urls:{deezer:d.link}}}
export type {SpotifyTrack,AppleResource,DeezerData};
